version: "3.9"

services:
    database:
        image: postgres
        container_name: database-container
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=102030
            - POSTGRES_DB=apitypescript
        volumes:
            - pgdata:/data/postgres       
    
    
    app:
        build: .
        container_name: rentalx-container
        restart: always
        ports: 
            - 5002:5002
        volumes: 
            - .:/usr/app
        links: 
            - database
        depends_on:
            - database
        
        
volumes:
    pgdata:
        driver: local